version: "3.9"
services:

  authors:
    build:
      context: ./authors
      network: host
    ports:
      - "50051:50051"
    expose:
      - "50051"

  books:
    build:
      context: ./books
      network: host
    environment:
      - AUTHORSRPC_URL=authors:50051
    ports:
      - "50052:50052"
    expose:
      - "50052"

  frontend:
    build:
      context: ./frontend
      network: host
    environment:
      - BOOKS_RPC=books:50052
      - AUTHORS_RPC=authors:50051
    expose:
      - "8080"
    ports:
      - "8096:8080"

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    expose:
      - "5672"
      - "15672"
    ports:
      - "15672:15672"
      - "5672:5672"
